server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 121.199.47.185
    username: leyou
    password: leyou
    virtual-host: /leyou
#  redis:
#    host: 192.168.1.104
ly:
  sms:
    accessKeyId: LTAI4FsjTpnVoZqa16Mwgtjv  # 自己的accessKeyId
    accessKeySecret: BuWfUTkdKAK8UxROuCO9hvsRJ6Oofl # 自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_177251132 # 模板名称 sms参数均少一位，ID密码请去阿里云官方申请